In [1]:
import pandas as pd
df=pd.read_csv('../sukkiri-ml2-codes/datafiles/Boston.csv')
df.head(2)

,CRIME,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,LSTAT,PRICE
0,high,0.0,18.10,0,0.718,3.561,87.9,1.6132,24.0,666,20.2,7.12,27.5
1,low,0.0,8.14,0,0.538,5.950,82.0,3.9900,4.0,307,21.0,27.71,13.2

In [2]:
#ダミー変数化
df2=df.fillna(df.mean(numeric_only=True))

dummy=pd.get_dummies(df2['CRIME'],drop_first=True,dtype=int)
df3=df2.join(dummy)
df3=df3.drop(['CRIME'],axis=1)

df3.head(2)

,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,LSTAT,PRICE,low,very_low
0,0.0,18.10,0,0.718,3.561,87.9,1.6132,24.0,666,20.2,7.12,27.5,0,0
1,0.0,8.14,0,0.538,5.950,82.0,3.9900,4.0,307,21.0,27.71,13.2,1,0

In [3]:
#標準化
from sklearn.preprocessing import StandardScaler

df4=df3.astype('float')
sc=StandardScaler()
sc_df=sc.fit_transform(df4)

In [4]:
#主成分分析の実施
from sklearn.decomposition import PCA

model=PCA(n_components=2,whiten=True)  #モデルの作成

In [ ]:
#モデルに学習させる
model.fit(sc_df)