#機械学習の勉強

In [1]:
import pandas as pd

In [ ]:
#機械学習基礎文法
date=[ 
    [160,161,150,60],
    [162,170,169,180]
]

#データフレームの作成
df=pd.DataFrame(date,index=['ハピ','チャパ'],columns=['4月','5月','6月','7月'])

In [3]:
df['5月']

ハピ     161
チャパ    170
Name: 5月, dtype: int64

In [4]:
df[['4月','6月']]

      4月   6月
ハピ   160  150
チャパ  162  169

In [5]:
print(type(df['5月']))
print(type(df[['4月','6月']]))

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>

In [6]:
#決定木
from sklearn import tree
x_col=df[['4月','5月','6月']]
t_col=df[['7月']]

model=tree.DecisionTreeClassifier(random_state=0)
model.fit(x_col,t_col)

DecisionTreeClassifier(random_state=0)

In [7]:
chipi=[[160,140,130]]
chipi_df=pd.DataFrame(chipi,
                      columns=x_col.columns)
model.predict(chipi_df)

array([60])

In [8]:
dubi=[150,40,190]
daba=[30,199,200]
new_data=pd.DataFrame([dubi,daba],
                      columns=x_col.columns)
model.predict(new_data)

array([ 60, 180])

In [9]:
model.score(x_col,t_col)

1.0

In [12]:
#4-1
scores=[
    [70,80],
    [72,85],
    [75,79],
    [80,92]
]
scores_df=pd.DataFrame(scores,columns=['データベースの試験得点','ネットワークの試験得点'])

scores_df

   データベースの試験得点  ネットワークの試験得点
0           70           80
1           72           85
2           75           79
3           80           92

In [14]:
#4-2
scores_df.index=['一郎','次郎','三郎','太郎']
scores_df

    データベースの試験得点  ネットワークの試験得点
一郎           70           80
次郎           72           85
三郎           75           79
太郎           80           92

In [16]:
#4-3
ex1_df = pd.read_csv(r'C:\Users\natsu\Desktop\機械学習\datafiles\ex1.csv')

In [17]:
#4-4
print(ex1_df.index)

Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
       72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
       90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
      dtype='int64')

In [18]:
#4-5
print(ex1_df.columns)

Index(['x0', 'x1', 'x2', 'x3', 'target'], dtype='object')

In [23]:
#4-6
col=['x0','x2']
print(ex1_df[col])
display(ex1_df[col])

          x0        x2
0   4.831144  5.082239
1   1.460716  7.632439
2   4.011018  5.935904
3   5.982382  3.890340
4   5.439188  4.827872
..       ...       ...
95  4.343917  5.925124
96  5.612101  4.338867
97  3.375022  6.534891
98  4.069721  5.884516
99  4.079704  5.657731

[100 rows x 2 columns]

          x0        x2
0   4.831144  5.082239
1   1.460716  7.632439
2   4.011018  5.935904
3   5.982382  3.890340
4   5.439188  4.827872
..       ...       ...
95  4.343917  5.925124
96  5.612101  4.338867
97  3.375022  6.534891
98  4.069721  5.884516
99  4.079704  5.657731

[100 rows x 2 columns]

In [20]:
%pip install polars==1.6.0

Collecting polars==1.6.0
  Downloading polars-1.6.0-cp38-abi3-win_amd64.whl.metadata (14 kB)
Downloading polars-1.6.0-cp38-abi3-win_amd64.whl (31.4 MB)
   ---------------------------------------- 0.0/31.4 MB ? eta -:--:--
   --- ------------------------------------ 2.9/31.4 MB 15.5 MB/s eta 0:00:02
   --------- ------------------------------ 7.3/31.4 MB 19.9 MB/s eta 0:00:02
   --------- ------------------------------ 7.3/31.4 MB 19.9 MB/s eta 0:00:02
   ------------ --------------------------- 9.4/31.4 MB 13.0 MB/s eta 0:00:02
   ------------------ --------------------- 14.7/31.4 MB 14.1 MB/s eta 0:00:02
   ---------------------- ----------------- 17.8/31.4 MB 14.3 MB/s eta 0:00:01
   -------------------------- ------------- 20.7/31.4 MB 14.2 MB/s eta 0:00:01
   ----------------------------- ---------- 23.1/31.4 MB 14.7 MB/s eta 0:00:01
   --------------------------------- ------ 26.5/31.4 MB 14.0 MB/s eta 0:00:01
   -------------------------------------- - 30.4/31.4 MB 15.0 MB/s eta 0:00:01
   ---------------------------------------- 31.4/31.4 MB 13.9 MB/s  0:00:02
Installing collected packages: polars
Successfully installed polars-1.6.0
Note: you may need to restart the kernel to use updated packages.

In [21]:
import polars as pl
df=pl.read_csv(r'C:\Users\natsu\Desktop\機械学習\datafiles\KvsT.csv')
df.head(2)

shape: (2, 4)
┌──────┬──────┬──────┬────────┐
│ 身長 ┆ 体重 ┆ 年代 ┆ 派閥   │
│ ---  ┆ ---  ┆ ---  ┆ ---    │
│ i64  ┆ i64  ┆ i64  ┆ str    │
╞══════╪══════╪══════╪════════╡
│ 170  ┆ 60   ┆ 10   ┆ きのこ │
│ 172  ┆ 65   ┆ 20   ┆ きのこ │
└──────┴──────┴──────┴────────┘

In [22]:
print(df.columns)
df.select(['身長','派閥']).head(2)

['身長', '体重', '年代', '派閥']

shape: (2, 2)
┌──────┬────────┐
│ 身長 ┆ 派閥   │
│ ---  ┆ ---    │
│ i64  ┆ str    │
╞══════╪════════╡
│ 170  ┆ きのこ │
│ 172  ┆ きのこ │
└──────┴────────┘

In [1]:
import sys
print(sys.executable)

c:\Users\natsu\anaconda3\python.exe