#機械学習の勉強

In [1]:
import pandas as pd
df=pd.read_csv(r'C:\Users\natsu\Desktop\machine_learning\datafiles\ex4.csv')

In [2]:
#7-1
df.head(3)

   class  dept_id  sex      score
0      3        0    1  60.170169
1      3        5    1  86.610078
2      2        6    1  69.761279

In [ ]:
#7-2
male_count=df['sex'].sum()
people_count=df['sex'].count()

male_rate=male_count/people_count
print(male_rate)

0.5133333333333333

In [5]:
#7-3
df.groupby('class')['score'].mean()

class
0    68.850195
1    69.510764
2    71.611092
3    67.572909
4    68.814253
Name: score, dtype: float64

In [ ]:
#7-4    ア２  イ0
pd.pivot_table(df,index='class',columns='sex',values='score')

sex            0          1
class
0      68.358569  69.274011
1      67.472218  71.379432
2      71.704884  71.532109
3      63.897676  72.013815
4      69.952314  67.676191

In [24]:
#7-5
df_dept_id=pd.get_dummies(df['dept_id'],drop_first=True,dtype=int)
df2=pd.concat([df,df_dept_id],axis=1)
df2=df2.drop('dept_id',axis=1)
display(df2.head(4))

#7-6  D

   class  sex      score  1  2  3  4  5  6
0      3    1  60.170169  0  0  0  0  0  0
1      3    1  86.610078  0  0  0  0  1  0
2      2    1  69.761279  0  0  0  0  0  1
3      2    1  62.597242  0  0  0  0  1  0

In [23]:
df4=pd.read_csv(r'C:\Users\natsu\Desktop\machine_learning\datafiles\for_natsu_test.csv')
print(df['sex'].mean())
print(df4['sex'].mean())

0.5133333333333333
0.5133333333333333

In [25]:
print(df['dept_id'].max())
print(df['dept_id'].min())

6
0