第12章

In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler  #標準化
from sklearn.linear_model import LogisticRegression  #ロジスティク回帰

In [6]:
df=pd.read_csv('../sukkiri-ml2-codes/datafiles/iris.csv')
display(df.head(3))

   がく片長さ  がく片幅  花弁長さ   花弁幅           種類
0   0.22  0.63  0.08  0.04  Iris-setosa
1   0.17  0.42  0.35  0.04  Iris-setosa
2   0.11  0.50  0.13  0.04  Iris-setosa

In [7]:
#欠損値を補完
df_mean=df.mean(numeric_only=True)
train2=df.fillna(df_mean)

#x,yに分割
x=train2.loc[:,:'花弁幅']
y=train2['種類']

#標準化
sc=StandardScaler()
new=sc.fit_transform(x)

#訓練データと検証データに分割（テストデータへの分割は省略するみたい）
x_train,x_val,y_train,y_val=train_test_split(new,y,test_size=0.2,random_state=0)

In [8]:
model=LogisticRegression(random_state=0,C=0.1,multi_class='auto',solver='lbfgs')

model.fit(x_train,y_train)
print(model.score(x_train,y_train))
print(model.score(x_val,y_val))

0.8666666666666667
0.8333333333333334

c:\Users\natsu\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1272: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.8. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

In [9]:
#係数の確認
model.coef_

array([[-0.53168668,  0.48573155, -0.52638431, -0.83213317],
       [ 0.09482289, -0.44707757, -0.00107471, -0.04407356],
       [ 0.4368638 , -0.03865398,  0.52745902,  0.87620673]])

In [10]:
#新規データでの予測
x_new=[[1,2,3,4]]
model.predict(x_new)

array(['Iris-virginica'], dtype=object)

In [12]:
model.predict_proba(x_new)

array([[4.02790964e-05, 3.02983301e-03, 9.96929888e-01]])

ランダムフォレストの実装

In [13]:
df=pd.read_csv('../sukkiri-ml2-codes/datafiles/Survived.csv')
display(df.head(3))

   PassengerId  Survived  Pclass  ...     Fare  Cabin  Embarked
0            1         0       3  ...   7.2500    NaN         S
1            2         1       1  ...  71.2833    C85         C
2            3         1       3  ...   7.9250    NaN         S

[3 rows x 11 columns]

In [ ]:
def fill_age(df,pclass,survived,value):
    joken1 = (df['Pclass']==pclass)
    joken2 = (df['Survived']==survived)
    joken3 = df['Age'].isnull()
    df.loc[(joken1)&(joken2)&(joken3),'Age']=value
    return df