In [6]:
#import
import pandas as pd

from sklearn.model_selection import train_test_split  #データの分割
from sklearn.preprocessing import StandardScaler  #標準化
from sklearn.covariance import MinCovDet  #マハラノビス距離

In [7]:
#データの前処理
df=pd.read_csv('sukkiri-ml-codes (1)\datafiles\Bank.csv')
df.head(5)

,id,age,job,marital,education,default,amount,housing,loan,contact,day,month,duration,campaign,previous,y
0,1,39,blue-collar,married,secondary,no,1756.0,yes,no,cellular,3,apr,370.055237,1,0,1
1,2,51,entrepreneur,married,primary,no,1443.0,no,no,cellular,18,feb,233.998933,10,0,1
2,3,36,management,single,tertiary,no,436.0,no,no,cellular,13,apr,NaN,1,2,0
3,4,63,retired,married,secondary,no,474.0,no,no,cellular,25,jan,252.525808,1,0,0
4,5,31,management,single,tertiary,no,354.0,no,no,cellular,30,apr,NaN,1,2,0

In [8]:
#ダミー変数化
str_col_name=['job','default','marital','education','housing','loan','contact','month']
str_df = df[str_col_name]  #文字列を抜き出す
str_df2=pd.get_dummies(str_df,drop_first=True)  #複数列を一気にダミー変数化

num_df = df.drop(str_col_name,axis=1)  #数値列を抜き出す
df2 = pd.concat([num_df,str_df2,str_df],axis=1)  #結合(今後の集計の利便性も考慮してstr_dfも結合しておく)


#訓練&検証データとテストデータに分割
train_val,test = train_test_split(df2,test_size=0.1,random_state=9)
train_val.head()

,id,age,amount,day,duration,campaign,previous,y,job_blue-collar,job_entrepreneur,...,month_oct,month_sep,job,default,marital,education,housing,loan,contact,month
13378,13379,46,0.0,10,378.293875,1,0,1,False,False,...,False,False,unemployed,no,married,tertiary,yes,no,cellular,jul
3800,3801,41,-333.0,30,300.845752,3,2,0,True,False,...,False,False,blue-collar,no,divorced,secondary,yes,no,cellular,jan
10398,10399,30,5389.0,6,159.053623,3,0,1,False,False,...,False,False,management,no,single,tertiary,no,no,cellular,aug
23401,23402,39,255.0,5,334.802583,1,0,0,False,False,...,False,False,management,no,single,tertiary,yes,no,sending _document,may
26223,26224,47,33.0,5,NaN,1,0,1,False,False,...,False,False,services,no,single,secondary,yes,no,cellular,may

In [ ]:
#不要な特徴量の削除
num_df=train_val.drop(str_col_name,axis=1)
num_df=num_df.drop('id',axis=1)
num_df2=num_df.dropna()


#マハラノビス距離を求める
mcd2 =MinCovDet(random_state=0,support_fraction=0.7)
mcd2.fit(num_df2)

dis =mcd2.mahalanobis(num_df2)
dis=pd.Series(dis)
dis.plot(kind="box")
no=dis[dis>300000].index
#先頭から2561番目が外れ値となる事が分かったので９章の付録で紹介したilocを利用する
no=num_df2.iloc[no[0]:(no[0]+1),:].index
train_val2 = train_val.drop(no)d

SyntaxError: invalid syntax (3644955550.py, line 10)

リッジ回帰

In [ ]:
import