Useful_code_summary_for_machine_learning

In [1]:
import pandas as pd

In [2]:
#確認したいDataFrame → display(df) または最後の行に df
#確認したい文字列や数値 → print()
ex1_df = pd.read_csv(r'C:\Users\natsu\Desktop\machine_learning\datafiles\ex1.csv')
col=['x0','x2']
print(ex1_df[col])
display(ex1_df[col])

          x0        x2
0   4.831144  5.082239
1   1.460716  7.632439
2   4.011018  5.935904
3   5.982382  3.890340
4   5.439188  4.827872
..       ...       ...
95  4.343917  5.925124
96  5.612101  4.338867
97  3.375022  6.534891
98  4.069721  5.884516
99  4.079704  5.657731

[100 rows x 2 columns]

          x0        x2
0   4.831144  5.082239
1   1.460716  7.632439
2   4.011018  5.935904
3   5.982382  3.890340
4   5.439188  4.827872
..       ...       ...
95  4.343917  5.925124
96  5.612101  4.338867
97  3.375022  6.534891
98  4.069721  5.884516
99  4.079704  5.657731

[100 rows x 2 columns]

In [6]:
#基本のコード

print(ex1_df.shape)  #データフレームのデータ数と列数を表示
print()
print(ex1_df.dtypes)  #各列のデータ型を表示
print()
print(ex1_df.nunique())  #各列に含まれる要素の種類を表示
print()
print(ex1_df.isnull().sum())  #欠損値の個数を表示
print()
print(ex1_df.columns)  #列一覧を表示

(100, 5)

x0        float64
x1        float64
x2        float64
x3        float64
target      int64
dtype: object

x0        100
x1        100
x2        100
x3        100
target      2
dtype: int64

x0        0
x1        0
x2        0
x3        0
target    0
dtype: int64

Index(['x0', 'x1', 'x2', 'x3', 'target'], dtype='object')

In [4]:
#参照
df = pd.read_csv(r'C:\Users\natsu\Desktop\machine_learning\datafiles\ex1.csv')
df.head(2)

         x0        x1        x2        x3  target
0  4.831144  4.695477  5.082239  4.501977       0
1  1.460716  1.216714  7.632439  2.359443       0

In [5]:
#pandasの考え方　　行単位 → 同一人物の複数指標　　列単位 → 複数人物の同一指標

In [8]:
#いろいろな個数カウント

#シンプルに頻度を知りたい
print('value_counts構文')
print(df.value_counts())

#複数列を組み合わせてカウントしたい
print('value_counts構文')
print(df.value_counts())
print(df.groupby(['x0','x1']).size())

#欠損を考慮した列ごとの要素数 
print('count構文')
print(df.count())

#全行数 
print('len構文')
print(len(df))

#辞書的に扱いたい 
print('Counter構文')
from collections import Counter
counts = Counter(df["x1"])
print(counts)

value_counts構文
x0        x1        x2        x3        target
0.320782  2.518524  9.361250  9.069262  1         1
5.612101  5.065338  4.338867  3.689948  0         1
6.008353  5.552547  4.066389  4.176480  0         1
5.982382  4.965863  3.890340  2.480491  0         1
5.950302  5.983260  4.281807  5.611331  1         1
                                                 ..
4.267327  4.657428  5.698957  5.775087  1         1
4.219458  4.637323  5.745419  5.832558  1         1
4.181685  4.042069  5.579562  4.139900  0         1
4.163588  4.006118  5.587217  4.076582  0         1
8.644794  7.185841  1.691293  2.589065  1         1
Name: count, Length: 100, dtype: int64
value_counts構文
x0        x1        x2        x3        target
0.320782  2.518524  9.361250  9.069262  1         1
5.612101  5.065338  4.338867  3.689948  0         1
6.008353  5.552547  4.066389  4.176480  0         1
5.982382  4.965863  3.890340  2.480491  0         1
5.950302  5.983260  4.281807  5.611331  1         1
                                                 ..
4.267327  4.657428  5.698957  5.775087  1         1
4.219458  4.637323  5.745419  5.832558  1         1
4.181685  4.042069  5.579562  4.139900  0         1
4.163588  4.006118  5.587217  4.076582  0         1
8.644794  7.185841  1.691293  2.589065  1         1
Name: count, Length: 100, dtype: int64
x0        x1
0.320782  2.518524    1
1.422334  3.137378    1
1.460716  1.216714    1
1.906029  3.387374    1
2.288733  2.058203    1
                     ..
7.259119  7.081245    1
7.299530  6.833727    1
7.344195  7.215791    1
7.517591  6.726329    1
8.644794  7.185841    1
Length: 100, dtype: int64
count構文
x0        100
x1        100
x2        100
x3        100
target    100
dtype: int64
len構文
100
Counter構文
Counter({4.6954769763415936: 1, 1.21671437314972: 1, 4.515939301610963: 1, 4.965862552684809: 1, 5.911559862466819: 1, 5.091764126624911: 1, 4.592533639978782: 1, 4.277726193315341: 1, 5.552546619194792: 1, 5.697922101549842: 1, 4.628921837893813: 1, 6.545609003138795: 1, 4.520489130014711: 1, 5.365566633729312: 1, 5.494361484965268: 1, 6.204114294030895: 1, 7.185840818304301: 1, 6.267679251746616: 1, 6.833727425396074: 1, 4.966728152294837: 1, 4.006117700724219: 1, 5.983259704450294: 1, 2.5751179087138567: 1, 4.669927084699519: 1, 5.7905593770736346: 1, 2.9340871656860714: 1, 6.225467630346488: 1, 4.878075522908135: 1, 6.321718333323045: 1, 5.828155720642798: 1, 6.384334305218927: 1, 4.85533160943516: 1, 3.7159144145275738: 1, 7.2157913408726415: 1, 5.607669949724545: 1, 5.984293792330268: 1, 4.152894716968018: 1, 4.987428885475423: 1, 3.754405161360519: 1, 6.282412778280228: 1, 2.7921008184277443: 1, 2.829016032962726: 1, 5.5707321399335: 1, 4.184859311389486: 1, 5.017293335746925: 1, 6.128277719284439: 1, 4.708613241884427: 1, 4.042069332373026: 1, 7.081244592450352: 1, 5.938564470703184: 1, 6.883123562743818: 1, 4.556194057536088: 1, 5.696962564633253: 1, 3.207041817423087: 1, 5.977124558990552: 1, 4.766827333262018: 1, 5.522558345559292: 1, 4.94431616251783: 1, 2.518999401715748: 1, 4.637322884875328: 1, 3.613897648753804: 1, 6.1896649916325295: 1, 4.58892326338826: 1, 4.716820731936165: 1, 2.0582030918652547: 1, 4.958296865640501: 1, 4.657427513895197: 1, 4.261869416268166: 1, 6.111991288410792: 1, 2.4952822813794957: 1, 5.467897215183098: 1, 6.451301832391036: 1, 4.724017351645228: 1, 4.244144791090902: 1, 4.36750761840156: 1, 3.3873744250376423: 1, 5.424950480125832: 1, 5.437919490679804: 1, 6.47417145017733: 1, 5.6849344765054814: 1, 3.1373783881825545: 1, 3.751021124149572: 1, 6.726328542665042: 1, 2.5185235444567: 1, 4.361644210773112: 1, 5.849847313670853: 1, 5.8837487265131525: 1, 6.287998886332035: 1, 4.954407011800272: 1, 4.0599910787521605: 1, 5.36716119783568: 1, 4.556826012555936: 1, 6.610607594696302: 1, 6.5396960689893: 1, 6.487471622298438: 1, 5.549314808587919: 1, 5.065337834310653: 1, 4.1964231375326815: 1, 4.556587041858084: 1, 3.939690681542365: 1})

In [ ]:
'''
例えば、'class'列に'top','middle','low'のいずれかのデータが格納されていて、序列があるとする。
これは順序尺度なので回帰・分類の際に1,2,3に置き換えてよい。
どんなコードで置き換えられるか。
'''
#方法１
df['class'] = df['class'].replace({
    'low': 1,
    'middle': 2,
    'top': 3
})

#方法２
df['class'] = df['class'].map({
    'low': 1,
    'middle': 2,
    'top': 3
})

In [ ]:
#行番号を振り直したいとき
df = df.reset_index(drop=True)

In [ ]:
#標準化についての疑問
'''
下記のコードで、fit,transformはどう違いますか？
sc_model_x=StandardScaler()
sc_model_x.fit(x_train) 
sc_x_train=sc_model_x.transform(x_train) 

fit() の役割：「学習する」
fit() は、標準化に必要な情報をデータから計算して記憶するメソッドです。
StandardScaler の場合は、各列について平均,標準偏差を計算します。

transform() の役割：「変換する」
transform() は、fit() で求めた平均・標準偏差を使って実際に標準化します。
'''

In [ ]:
'''
データサイエンスで予測精度の向上のためにできること

・欠損値の埋め方の工夫（平均値、中央値、クロス集計）
・外れ値の除去
・予測に利用する目的変数の選定（散布図、相関係数の利用）
・多項式特徴量の追加（多項式回帰）
・交互作用特徴量の追加

・データを標準化する
・p値, VIFの計算
'''

In [ ]:
'''
df.loc[index,columns] → index行、col列の取り出し

データフレーム内に、該当する行・列がないときは、新たに行列が追加される
例
x['RM2'] = x['RM']**2　　　　RM2という列ができる
x.loc[:, 'RM2'] = x['RM']**2

x.loc[2000] = [10, 7, 8, 100]　　　2000という列ができる

'''

In [ ]:
'''
pandasでのcolumns,indexの扱い

columns と index は行名・列名を表す重要な用語ですが、「データの選択」に使うのではなく、「行名・列名そのものを取得・設定するための属性や引数」として使われます。

x.columns → 列名を取得・設定
x.index → 行名を取得・設定
x.loc[行, 列] → 行・列を指定してデータを取得・代入
x['列名'] → 列を取得・追加



① columns を使う場面

列名を確認する
print(x.columns)
Index(['RM', 'LSTAT', 'AGE'], dtype='object')

列名を変更する
x.columns = ['A', 'B', 'C']




② index を使う場面

行番号（インデックス）を確認する
print(x.index)
RangeIndex(start=0, stop=506, step=1)

インデックスを変更する
x.index = ['a', 'b', 'c', ...]



③ データを取り出すときは .loc

例えば
x.loc['a']
はインデックスが 'a' の行
'''

In [ ]:
#vscodeで横幅が長いdfを表示できないときの対処
display(df.T)   #転地して表示できるので横幅を気にしなくてよい
pd.set_option('display.max_columns', None)   # 全列表示
pd.set_option('display.width', None)         # 横幅制限を解除